'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings 自动保存功能"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://en.wikipedia.org/w/index.php?title=Special:Search&search=%22%s%22")>  _
        Public Property SearchEngine1() As String
            Get
                Return CType(Me("SearchEngine1"),String)
            End Get
            Set
                Me("SearchEngine1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.google.com/search?newwindow=1&ei=wvhFWumeD-mC0wKGmrDYDw&q=define%3A+%"& _ 
            "22%s%22")>  _
        Public Property SearchEngine2() As String
            Get
                Return CType(Me("SearchEngine2"),String)
            End Get
            Set
                Me("SearchEngine2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.bing.com/dict/search?q=%22%s%22")>  _
        Public Property SearchEngine3() As String
            Get
                Return CType(Me("SearchEngine3"),String)
            End Get
            Set
                Me("SearchEngine3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.google.com")>  _
        Public Property SearchEngine4() As String
            Get
                Return CType(Me("SearchEngine4"),String)
            End Get
            Set
                Me("SearchEngine4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("wiki百科")>  _
        Public Property SEname1() As String
            Get
                Return CType(Me("SEname1"),String)
            End Get
            Set
                Me("SEname1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("google词典")>  _
        Public Property SEname2() As String
            Get
                Return CType(Me("SEname2"),String)
            End Get
            Set
                Me("SEname2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("bing双语例句")>  _
        Public Property SEname3() As String
            Get
                Return CType(Me("SEname3"),String)
            End Get
            Set
                Me("SEname3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("google")>  _
        Public Property SEname4() As String
            Get
                Return CType(Me("SEname4"),String)
            End Get
            Set
                Me("SEname4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("基本信息")>  _
        Public Property SEtab1() As String
            Get
                Return CType(Me("SEtab1"),String)
            End Get
            Set
                Me("SEtab1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("英语")>  _
        Public Property SEtab2() As String
            Get
                Return CType(Me("SEtab2"),String)
            End Get
            Set
                Me("SEtab2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("日语")>  _
        Public Property SEtab3() As String
            Get
                Return CType(Me("SEtab3"),String)
            End Get
            Set
                Me("SEtab3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("法语")>  _
        Public Property SEtab4() As String
            Get
                Return CType(Me("SEtab4"),String)
            End Get
            Set
                Me("SEtab4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("baidu")>  _
        Public Property SEname11() As String
            Get
                Return CType(Me("SEname11"),String)
            End Get
            Set
                Me("SEname11") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("baidu")>  _
        Public Property SEname12() As String
            Get
                Return CType(Me("SEname12"),String)
            End Get
            Set
                Me("SEname12") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("baidu")>  _
        Public Property SEname13() As String
            Get
                Return CType(Me("SEname13"),String)
            End Get
            Set
                Me("SEname13") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("baidu")>  _
        Public Property SEname14() As String
            Get
                Return CType(Me("SEname14"),String)
            End Get
            Set
                Me("SEname14") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("baidu")>  _
        Public Property SEname21() As String
            Get
                Return CType(Me("SEname21"),String)
            End Get
            Set
                Me("SEname21") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("baidu")>  _
        Public Property SEname22() As String
            Get
                Return CType(Me("SEname22"),String)
            End Get
            Set
                Me("SEname22") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("baidu")>  _
        Public Property SEname23() As String
            Get
                Return CType(Me("SEname23"),String)
            End Get
            Set
                Me("SEname23") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("baidu")>  _
        Public Property SEname24() As String
            Get
                Return CType(Me("SEname24"),String)
            End Get
            Set
                Me("SEname24") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("baidu")>  _
        Public Property SEname31() As String
            Get
                Return CType(Me("SEname31"),String)
            End Get
            Set
                Me("SEname31") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("baidu")>  _
        Public Property SEname32() As String
            Get
                Return CType(Me("SEname32"),String)
            End Get
            Set
                Me("SEname32") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("baidu")>  _
        Public Property SEname33() As String
            Get
                Return CType(Me("SEname33"),String)
            End Get
            Set
                Me("SEname33") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("baidu")>  _
        Public Property SEname34() As String
            Get
                Return CType(Me("SEname34"),String)
            End Get
            Set
                Me("SEname34") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.baidu.com")>  _
        Public Property SearchEngine11() As String
            Get
                Return CType(Me("SearchEngine11"),String)
            End Get
            Set
                Me("SearchEngine11") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.baidu.com")>  _
        Public Property SearchEngine12() As String
            Get
                Return CType(Me("SearchEngine12"),String)
            End Get
            Set
                Me("SearchEngine12") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.baidu.com")>  _
        Public Property SearchEngine13() As String
            Get
                Return CType(Me("SearchEngine13"),String)
            End Get
            Set
                Me("SearchEngine13") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.baidu.com")>  _
        Public Property SearchEngine14() As String
            Get
                Return CType(Me("SearchEngine14"),String)
            End Get
            Set
                Me("SearchEngine14") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.baidu.com")>  _
        Public Property SearchEngine21() As String
            Get
                Return CType(Me("SearchEngine21"),String)
            End Get
            Set
                Me("SearchEngine21") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.baidu.com")>  _
        Public Property SearchEngine22() As String
            Get
                Return CType(Me("SearchEngine22"),String)
            End Get
            Set
                Me("SearchEngine22") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.baidu.com")>  _
        Public Property SearchEngine23() As String
            Get
                Return CType(Me("SearchEngine23"),String)
            End Get
            Set
                Me("SearchEngine23") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.baidu.com")>  _
        Public Property SearchEngine24() As String
            Get
                Return CType(Me("SearchEngine24"),String)
            End Get
            Set
                Me("SearchEngine24") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.baidu.com")>  _
        Public Property SearchEngine31() As String
            Get
                Return CType(Me("SearchEngine31"),String)
            End Get
            Set
                Me("SearchEngine31") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.baidu.com")>  _
        Public Property SearchEngine32() As String
            Get
                Return CType(Me("SearchEngine32"),String)
            End Get
            Set
                Me("SearchEngine32") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.baidu.com")>  _
        Public Property SearchEngine33() As String
            Get
                Return CType(Me("SearchEngine33"),String)
            End Get
            Set
                Me("SearchEngine33") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.baidu.com")>  _
        Public Property SearchEngine34() As String
            Get
                Return CType(Me("SearchEngine34"),String)
            End Get
            Set
                Me("SearchEngine34") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property SetTabID() As String
            Get
                Return CType(Me("SetTabID"),String)
            End Get
            Set
                Me("SetTabID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollX1() As String
            Get
                Return CType(Me("ScrollX1"),String)
            End Get
            Set
                Me("ScrollX1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollX2() As String
            Get
                Return CType(Me("ScrollX2"),String)
            End Get
            Set
                Me("ScrollX2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollX3() As String
            Get
                Return CType(Me("ScrollX3"),String)
            End Get
            Set
                Me("ScrollX3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollX4() As String
            Get
                Return CType(Me("ScrollX4"),String)
            End Get
            Set
                Me("ScrollX4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollY1() As String
            Get
                Return CType(Me("ScrollY1"),String)
            End Get
            Set
                Me("ScrollY1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollY2() As String
            Get
                Return CType(Me("ScrollY2"),String)
            End Get
            Set
                Me("ScrollY2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollY3() As String
            Get
                Return CType(Me("ScrollY3"),String)
            End Get
            Set
                Me("ScrollY3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollY4() As String
            Get
                Return CType(Me("ScrollY4"),String)
            End Get
            Set
                Me("ScrollY4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Scale1() As String
            Get
                Return CType(Me("Scale1"),String)
            End Get
            Set
                Me("Scale1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Scale2() As String
            Get
                Return CType(Me("Scale2"),String)
            End Get
            Set
                Me("Scale2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Scale3() As String
            Get
                Return CType(Me("Scale3"),String)
            End Get
            Set
                Me("Scale3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Scale4() As String
            Get
                Return CType(Me("Scale4"),String)
            End Get
            Set
                Me("Scale4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollX11() As String
            Get
                Return CType(Me("ScrollX11"),String)
            End Get
            Set
                Me("ScrollX11") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollX12() As String
            Get
                Return CType(Me("ScrollX12"),String)
            End Get
            Set
                Me("ScrollX12") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollX13() As String
            Get
                Return CType(Me("ScrollX13"),String)
            End Get
            Set
                Me("ScrollX13") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollX14() As String
            Get
                Return CType(Me("ScrollX14"),String)
            End Get
            Set
                Me("ScrollX14") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollY11() As String
            Get
                Return CType(Me("ScrollY11"),String)
            End Get
            Set
                Me("ScrollY11") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollY12() As String
            Get
                Return CType(Me("ScrollY12"),String)
            End Get
            Set
                Me("ScrollY12") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollY13() As String
            Get
                Return CType(Me("ScrollY13"),String)
            End Get
            Set
                Me("ScrollY13") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollY14() As String
            Get
                Return CType(Me("ScrollY14"),String)
            End Get
            Set
                Me("ScrollY14") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Scale11() As String
            Get
                Return CType(Me("Scale11"),String)
            End Get
            Set
                Me("Scale11") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Scale12() As String
            Get
                Return CType(Me("Scale12"),String)
            End Get
            Set
                Me("Scale12") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Scale13() As String
            Get
                Return CType(Me("Scale13"),String)
            End Get
            Set
                Me("Scale13") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Scale14() As String
            Get
                Return CType(Me("Scale14"),String)
            End Get
            Set
                Me("Scale14") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollX21() As String
            Get
                Return CType(Me("ScrollX21"),String)
            End Get
            Set
                Me("ScrollX21") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollX22() As String
            Get
                Return CType(Me("ScrollX22"),String)
            End Get
            Set
                Me("ScrollX22") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollX23() As String
            Get
                Return CType(Me("ScrollX23"),String)
            End Get
            Set
                Me("ScrollX23") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollX24() As String
            Get
                Return CType(Me("ScrollX24"),String)
            End Get
            Set
                Me("ScrollX24") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Scale21() As String
            Get
                Return CType(Me("Scale21"),String)
            End Get
            Set
                Me("Scale21") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Scale22() As String
            Get
                Return CType(Me("Scale22"),String)
            End Get
            Set
                Me("Scale22") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Scale23() As String
            Get
                Return CType(Me("Scale23"),String)
            End Get
            Set
                Me("Scale23") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Scale24() As String
            Get
                Return CType(Me("Scale24"),String)
            End Get
            Set
                Me("Scale24") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollY21() As String
            Get
                Return CType(Me("ScrollY21"),String)
            End Get
            Set
                Me("ScrollY21") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollY22() As String
            Get
                Return CType(Me("ScrollY22"),String)
            End Get
            Set
                Me("ScrollY22") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollY23() As String
            Get
                Return CType(Me("ScrollY23"),String)
            End Get
            Set
                Me("ScrollY23") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollY24() As String
            Get
                Return CType(Me("ScrollY24"),String)
            End Get
            Set
                Me("ScrollY24") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollX31() As String
            Get
                Return CType(Me("ScrollX31"),String)
            End Get
            Set
                Me("ScrollX31") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollX32() As String
            Get
                Return CType(Me("ScrollX32"),String)
            End Get
            Set
                Me("ScrollX32") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollX33() As String
            Get
                Return CType(Me("ScrollX33"),String)
            End Get
            Set
                Me("ScrollX33") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollX34() As String
            Get
                Return CType(Me("ScrollX34"),String)
            End Get
            Set
                Me("ScrollX34") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollY31() As String
            Get
                Return CType(Me("ScrollY31"),String)
            End Get
            Set
                Me("ScrollY31") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollY32() As String
            Get
                Return CType(Me("ScrollY32"),String)
            End Get
            Set
                Me("ScrollY32") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollY33() As String
            Get
                Return CType(Me("ScrollY33"),String)
            End Get
            Set
                Me("ScrollY33") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ScrollY34() As String
            Get
                Return CType(Me("ScrollY34"),String)
            End Get
            Set
                Me("ScrollY34") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Scale31() As String
            Get
                Return CType(Me("Scale31"),String)
            End Get
            Set
                Me("Scale31") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Scale32() As String
            Get
                Return CType(Me("Scale32"),String)
            End Get
            Set
                Me("Scale32") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Scale33() As String
            Get
                Return CType(Me("Scale33"),String)
            End Get
            Set
                Me("Scale33") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Scale34() As String
            Get
                Return CType(Me("Scale34"),String)
            End Get
            Set
                Me("Scale34") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Autosave() As Boolean
            Get
                Return CType(Me("Autosave"),Boolean)
            End Get
            Set
                Me("Autosave") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("File Name Not Defined")>  _
        Public Property Autofilename() As String
            Get
                Return CType(Me("Autofilename"),String)
            End Get
            Set
                Me("Autofilename") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.WindowsApplication1.My.MySettings
            Get
                Return Global.WindowsApplication1.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
